### PR TITLE
replaced checkequal function with operator== for marray check

### PR DESCRIPTION
**Pull request by xtian-github**
Use operator== for marray value comparison

### CODE REVIEW

**Comment by bashbaug** [comment]
I'd love to find a way to simplify this but I don't think switching to `operator==` will work.

I tried this snippet:

```c++
  marray<int, 4> a{0, 0, 0, 0};
  marray<int, 4> b{0, 1, 2, 3};
  auto c0 = a == b;

  std::cout << "On the host:\n";
  std::cout << "a == b              : " << c0 << "\n";
  std::cout << "std::any_of(a == b) : " << std::any_of(c0.begin(), c0.end(), [](bool b){ return b; }) << "\n";
  std::cout << "std::all_of(a == b) : " << std::all_of(c0.begin(), c0.end(), [](bool b){ return b; }) << "\n";
```

My output is:

```
On the host:
a == b              : 1
std::any_of(a == b) : 1
std::all_of(a == b) : 0
```

I haven't quite traced what `operator==` is doing, but it definitely doesn't look like the right thing.

**Comment by xtian-github** [comment]
This is IR we have for marray<float, 4> res[32]
<51>         BEGIN REGION { }
<71>               + DO i1 = 0, 3, 1   <DO_LOOP>
<57>               |   %cmp2.i = (%res)[0][0].0[i1] == (%res)[0][16].0[i1];
<60>               |   (%retval.i)[0].0[i1] = %cmp2.i;
<71>               + END LOOP
<51>         END REGION

**Comment by bashbaug** [comment]
Following up: This shouldn't work, and the only reason it is working is because we have a bug in our headers: `if (res[0] == res[M/2])`.

It's currently "working" because it ends up in this function, which just returns the first element of the `marray`:

https://github.com/intel/llvm/blob/sycl/sycl/include/sycl/marray.hpp#L137

This function should only be enabled when `NumElements == 1`, but it's not due to a subtle `std::enable_if` bug - basically it should be using `std::enable_if_t` instead.  When this bug is fixed `if (res[0] == res[M/2])` will stop compiling... which is good because it's not doing what we want it to do right now anyhow!

I think we'll need to find an alternative way to simplify this sample instead.

**Comment by xtian-github** [comment]
I saw below code in the marray.hpp file. for __SYCL_RELLOGOP(==). 
friend marray<bool, NumElements> operator RELLOGOP(const marray &Lhs,        \
                                                     const marray &Rhs) {      \
    marray<bool, NumElements> Ret;                                             \
    for (size_t I = 0; I < NumElements; ++I) {                                 \
      Ret[I] = Lhs[I] RELLOGOP Rhs[I];                                         \
    }                                                                          \
    return Ret;                                                                \
  }                                                                            \
  template <typename T>                                                        \
  friend typename std::enable_if_t<std::is_convertible_v<T, DataT> &&          \
                                       (std::is_fundamental_v<T> ||            \
                                        std::is_same_v<T, half>),              \
                                   marray<bool, NumElements>>                  \
  operator RELLOGOP(const marray &Lhs, const T &Rhs) {                         \
    return Lhs RELLOGOP marray(static_cast<const DataT &>(Rhs));               \
  }                                                                            \
  template <typename T>                                                        \
  friend typename std::enable_if_t<std::is_convertible_v<T, DataT> &&          \
                                       (std::is_fundamental_v<T> ||            \
                                        std::is_same_v<T, half>),              \
                                   marray<bool, NumElements>>                  \
  operator RELLOGOP(const T &Lhs, const marray &Rhs) {                         \
    return marray(static_cast<const DataT &>(Lhs)) RELLOGOP Rhs;               \
  }

  __SYCL_RELLOGOP(==)
... .... ....

**Comment by xtian-github** [comment]
I was checking where the i1 "==" loop (in LLVM IR and HIR) comes from. It seems it comes from __SYCL_RELLOGOP(==) below. 

friend marray<bool, NumElements> operator RELLOGOP(const marray &Lhs,        \
                                                     const marray &Rhs) {      \
    marray<bool, NumElements> Ret;                                             \
    for (size_t I = 0; I < NumElements; ++I) {                                 \
      Ret[I] = Lhs[I] RELLOGOP Rhs[I];                                         \
    }                                                                          \
    return Ret;                                                                \
  }                                                                            \
  template <typename T>                                                        \
  friend typename std::enable_if_t<std::is_convertible_v<T, DataT> &&          \
                                       (std::is_fundamental_v<T> ||            \
                                        std::is_same_v<T, half>),              \
                                   marray<bool, NumElements>>                  \
  operator RELLOGOP(const marray &Lhs, const T &Rhs) {                         \
    return Lhs RELLOGOP marray(static_cast<const DataT &>(Rhs));               \
  }                                                                            \
  template <typename T>                                                        \
  friend typename std::enable_if_t<std::is_convertible_v<T, DataT> &&          \
                                       (std::is_fundamental_v<T> ||            \
                                        std::is_same_v<T, half>),              \
                                   marray<bool, NumElements>>                  \
  operator RELLOGOP(const T &Lhs, const marray &Rhs) {                         \
    return marray(static_cast<const DataT &>(Lhs)) RELLOGOP Rhs;               \
  }

  __SYCL_RELLOGOP(==)

**Comment by bashbaug** [comment]
Right, but `operator==` gives you a `marray<bool, N>` - see line 106 here:

https://registry.khronos.org/SYCL/specs/sycl-2020/html/sycl-2020.html#_math_array_interface

If we want to use the result of `operator==` in an if condition then we need to convert from `marray<bool, N>` to `bool` or similar... and there is no implicit way to do that, or at least there won't be when the bug gets fixed.

**Comment by xtian-github** [comment]
Right, the loop save == results into an array   (%retval.i)[0].0[i1] = %cmp2.i;

**Comment by xtian-github** [comment]
we need something like, all_true(retval[0][0:N]), or any_false(retval[0][0:N]) after loop.

**Comment by mkinsner** [comment]
Decision to close without merge, based on offline discussion

**Comment by xtian-github** [comment]
@mkinsner Thanks.

**Pull request closed without merging**
